package dev.msfjarvis.aps.gradle.versioning

const val VERSIONING_PROP_FILE = "version.properties"
const val VERSIONING_PROP_VERSION_NAME = "versioning-plugin.versionName"
const val VERSIONING_PROP_VERSION_CODE = "versioning-plugin.versionCode"
const val VERSIONING_PROP_COMMENT =
  """#
# This file was automatically generated by 'versioning-plugin'. DO NOT EDIT MANUALLY.
#"""
