/*
 * Copyright © Harsh Shandilya.
 * Use of this source code is governed by an MIT-style
 * license that can be found in the LICENSE file or at
 * https://opensource.org/licenses/MIT.
 */
package dev.msfjarvis.claw.gradle.versioning

const val VERSIONING_PROP_FILE = "version.properties"
const val VERSIONING_PROP_VERSION_NAME = "versioning-plugin.versionName"
const val VERSIONING_PROP_VERSION_CODE = "versioning-plugin.versionCode"
const val VERSIONING_PROP_COMMENT =
  """#
# This file was automatically generated by 'versioning-plugin'. DO NOT EDIT MANUALLY.
#"""
