-keepattributes *Annotation*, EnclosingMethod, InnerClasses
-dontwarn org.jetbrains.kotlin.**
-dontwarn androidx.compose.animation.tooling.ComposeAnimation
-dontwarn android.view.RenderNode
-dontwarn android.view.DisplayListCanvas
-dontwarn sun.misc.Unsafe
-dontobfuscate
-dontoptimize
