-keepattributes *Annotation*, EnclosingMethod, InnerClasses
-dontwarn org.jetbrains.kotlin.**
-dontwarn androidx.compose.animation.tooling.ComposeAnimation
-dontobfuscate
-dontoptimize
-keep class dev.msfjarvis.lobsters.model.** { *; }
