name: 'Setup Gradle'
description: 'Checks out the repository and sets up Java and Gradle'
inputs:
  token:
    description: 'token input for actions/checkout'
    required: false
    default: ${{ github.token }}
  fetch-depth:
    description: 'fetch-depth input for actions/checkout'
    required: false
    default: 1
  cache-read-only:
    description: 'cache-read-only input for gradle/actions/setup-gradle'
    required: false
    default: ${{ github.event.repository != null && github.ref_name != github.event.repository.default_branch }}
  dependency-graph:
    description: 'dependency-graph input for gradle/actions/setup-gradle'
    required: false
    default: 'disabled'
  persist-credentials:
    description: 'Control the actions/checkout persist-credentials setting'
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ inputs.token }}
        lfs: true
        persist-credentials: ${{ inputs.persist-credentials }}

    - name: Set up JDK
      uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
      with:
        distribution: temurin
        java-version: 23

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@cc4fc85e6b35bafd578d5ffbc76a5518407e1af0 # v4
      with:
        add-job-summary: always
        cache-read-only: ${{ inputs.cache-read-only }}
        dependency-graph: ${{ inputs.dependency-graph }}
        validate-wrappers: true
